Firmware Update for Allo

diff --git a/drivers/dahdi/firmware/Makefile b/drivers/dahdi/firmware/Makefile
--- a/drivers/dahdi/firmware/Makefile
+++ b/drivers/dahdi/firmware/Makefile
@@ -1,6 +1,6 @@
 #
 # DAHDI
-# 
+#
 # Makefile for firmware downloading/installation
 #
 # Copyright (C) 2007-2013, Digium, Inc.
@@ -41,10 +41,13 @@ A4A_VERSION:=a0017
 A4B_VERSION:=d001e
 
 FIRMWARE_URL:=http://downloads.digium.com/pub/telephony/firmware/releases
+FIRMWARE_URL_ALLO:=https://www.allo.com/firmware/releases
 
 ALL_FIRMWARE=FIRMWARE-OCT6114-032 FIRMWARE-OCT6114-064 FIRMWARE-OCT6114-128 FIRMWARE-OCT6114-256
 ALL_FIRMWARE+=FIRMWARE-TC400M FIRMWARE-HX8 FIRMWARE-VPMOCT032 FIRMWARE-TE820 FIRMWARE-TE133 FIRMWARE-TE134
-ALL_FIRMWARE+=FIRMWARE-A8A FIRMWARE-A8B FIRMWARE-A4A FIRMWARE-A4B FIRMWARE-TE435 FIRMWARE-TE436
+ALL_FIRMWARE+=FIRMWARE-A8A FIRMWARE-A8B FIRMWARE-A4A FIRMWARE-A4B FIRMWARE-TE435 FIRMWARE-TE436 FIRMWARE-allo-1PPCIe  FIRMWARE-allo-2PPCIe FIRMWARE-allo-4PPCI FIRMWARE-allo-4PPCIe FIRMWARE-allo-8PPCIe
+ALL_FIRMWARE+=FIRMWARE-allo-3aCP1e FIRMWARE-allo-3aCP2e FIRMWARE-allo-3aCP4e
+ALL_FIRMWARE+=FIRMWARE-allo-4aCP1e FIRMWARE-allo-4aCP2e FIRMWARE-allo-4aCP4e FIRMWARE-allo-4aCP8e
 
 # Firmware files should use the naming convention: dahdi-fw-<base name>-<sub name>-<version> or dahdi-fw-<base name>-<version>
 # First example: dahdi-fw-oct6114-064-1.05.01
@@ -69,7 +72,18 @@ FIRMWARE:=$(FIRMWARE:FIRMWARE-A8A=dahdi-fw-a8b-$(A8B_VERSION).tar.gz)
 FIRMWARE:=$(FIRMWARE:FIRMWARE-A8B=dahdi-fw-a8a-$(A8A_VERSION).tar.gz)
 FIRMWARE:=$(FIRMWARE:FIRMWARE-A4A=dahdi-fw-a4b-$(A4B_VERSION).tar.gz)
 FIRMWARE:=$(FIRMWARE:FIRMWARE-A4B=dahdi-fw-a4a-$(A4A_VERSION).tar.gz)
-
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-1PPCIe=allo-dahdi-fw-2aCP1e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-2PPCIe=allo-dahdi-fw-2aCP2e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-4PPCIe=allo-dahdi-fw-2aCP4e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-8PPCIe=allo-dahdi-fw-2aCP8e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-4PPCI=allo-dahdi-fw-2aCP4.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-3aCP1e=allo-dahdi-fw-3aCP1e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-3aCP2e=allo-dahdi-fw-3aCP2e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-3aCP4e=allo-dahdi-fw-3aCP4e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-4aCP1e=allo-dahdi-fw-4aCP1e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-4aCP2e=allo-dahdi-fw-4aCP2e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-4aCP4e=allo-dahdi-fw-4aCP4e.tar.gz)
+FIRMWARE:=$(FIRMWARE:FIRMWARE-allo-4aCP8e=allo-dahdi-fw-4aCP8e.tar.gz)
 FWLOADERS:=dahdi-fwload-vpmadt032-$(VPMADT032_VERSION).tar.gz
 
 # Build a list of object files if hotplug will not be used
@@ -100,6 +114,8 @@ dist-clean: clean
 	rm -f dahdi-fw-*.tar.gz
 	rm -f dahdi-fwload-*.tar.gz
 	rm -f make_firmware_object
+	rm -f allo-dahdi-fw-*.bin
+	rm -f allo-dahdi-fw-*.tar.gz
 
 # Clean up anything we built
 clean:
@@ -112,7 +128,13 @@ dahdi-fw-%.tar.gz:
 		if test ! -f $@; then $(DOWNLOAD) $(WGET_ARGS) $(FIRMWARE_URL)/$@; fi; \
 		if test ! -f $@; then exit 1; fi; \
 	fi
-
+allo-dahdi-fw%.tar.gz:
+	@if ( [ "$(HOTPLUG_FIRMWARE)" = "no" ] ) || ( [ -d $(DESTDIR)/usr/lib/hotplug/firmware ] && ! [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.$(subst .tar.gz,,$*) ] ) || ( [ -d $(DESTDIR)/lib/firmware ] && ! [ -f $(DESTDIR)/lib/firmware/.$(subst .tar.gz,,$*) ] ); then \
+                echo "Attempting to download $@"; \
+                if test ! -f $@; then $(DOWNLOAD) $(WGET_ARGS) $(FIRMWARE_URL_ALLO)/$@ --no-check-certificate; fi; \
+                if test ! -f $@; then exit 1; fi; \
+                (cat $@ | gzip -d | tar --no-same-owner -xf -) \
+        fi
 firmware-loaders: $(FWLOADERS)
 
 .PHONY: dahdi-fwload-vpmadt032-$(VPMADT032_VERSION).tar.gz
@@ -145,16 +167,181 @@ hotplug-install: $(DESTDIR)/usr/lib/hotplug/firmware $(DESTDIR)/lib/firmware $(F
 	@$(call RUN_INST,dahdi-fw-a8b,$(A8B_VERSION))
 	@$(call RUN_INST,dahdi-fw-a4a,$(A4A_VERSION))
 	@$(call RUN_INST,dahdi-fw-a4b,$(A4B_VERSION))
+######################ALLO#################################
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP1e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP1e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-2aCP1e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP1e
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP1e
+	@install -m 644 allo-dahdi-fw-2aCP1e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP1e
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP1e
+else
+	@echo "Firmware of ALLO card allo-dahdi-fw-2aCP1e.bin  is already installed with required version"
+endif
+
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP2e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP2e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-2aCP2e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP2e
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP2e
+	@install -m 644 allo-dahdi-fw-2aCP2e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP2e
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP2e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-2aCP2e.bin is already installed with required version"
+endif
+
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP4 ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP4 ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-2aCP4.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP4
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP4
+	@install -m 644 allo-dahdi-fw-2aCP4.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP4
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP4
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-2aCP4.bin is already installed with required version"
+endif
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP4e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP4e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-2aCP4e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP4e
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP4e
+	@install -m 644 allo-dahdi-fw-2aCP4e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP4e
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP4e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-2aCP4e.bin  is already installed with required version"
+endif
+
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP8e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP8e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-2aCP8e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP8e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-2aCP8e
+	@install -m 644 allo-dahdi-fw-2aCP8e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP8e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-2aCP8e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-2aCP8e.bin  is already installed with required version"
+endif
+
+#firmware with license
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP1e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP1e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-3aCP1e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP1e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP1e
+	@install -m 644 allo-dahdi-fw-3aCP1e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP1e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP1e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-3aCP1e.bin  is already installed with required version"
+endif
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP2e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP2e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-3aCP2e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP2e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP2e
+	@install -m 644 allo-dahdi-fw-3aCP2e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP2e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP2e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-3aCP2e.bin  is already installed with required version"
+endif
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP4e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP4e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-3aCP4e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP4e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP4e
+	@install -m 644 allo-dahdi-fw-3aCP4e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP4e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-3aCP4e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-3aCP4e.bin  is already installed with required version"
+endif
+
+#firmware without license
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP1e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP1e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-4aCP1e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP1e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP1e
+	@install -m 644 allo-dahdi-fw-4aCP1e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP1e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP1e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-4aCP1e.bin  is already installed with required version"
+endif
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP2e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP2e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-4aCP2e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP2e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP2e
+	@install -m 644 allo-dahdi-fw-4aCP2e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP2e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP2e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-4aCP2e.bin  is already installed with required version"
+endif
+
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP4e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP4e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-4aCP4e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP4e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP4e
+	@install -m 644 allo-dahdi-fw-4aCP4e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP4e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP4e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-4aCP4e.bin  is already installed with required version"
+endif
+ifeq ($(shell if ( [ -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP8e ] ) && ( [ -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP8e ] ); then echo "no"; else echo "yes"; fi),yes)
+
+	@echo "Installing ALLO firmwares to hotplug firmware directories"
+	@install -m 644 allo-dahdi-fw-4aCP8e.bin $(DESTDIR)/usr/lib/hotplug/firmware
+	@rm -rf $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-4aCP8e*
+	@touch $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw-3aCP8e
+	@install -m 644 allo-dahdi-fw-4aCP8e.bin $(DESTDIR)/lib/firmware
+	@rm -rf $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP8e*
+	@touch $(DESTDIR)/lib/firmware/.allo-dahdi-fw-4aCP8e
+else
+	@echo "Firmware of ALLO cards allo-dahdi-fw-4aCP8e.bin  is already installed with required version"
+endif
+#########################END######################################
 
 # Uninstall any installed dahdi firmware images from hotplug firmware directories
 hotplug-uninstall:
 	if [ -d $(DESTDIR)/usr/lib/hotplug/firmware ]; then \
 		rm -f $(DESTDIR)/usr/lib/hotplug/firmware/dahdi-fw-*.bin; \
 		rm -f $(DESTDIR)/usr/lib/hotplug/firmware/.dahdi-fw*; \
+		rm -f $(DESTDIR)/usr/lib/hotplug/firmware/allo-dahdi-fw-*.bin; \
+		rm -f $(DESTDIR)/usr/lib/hotplug/firmware/.allo-dahdi-fw*; \
 	fi
 	if [ -d $(DESTDIR)/lib/firmware ]; then \
 		rm -f $(DESTDIR)/lib/firmware/dahdi-fw-*.bin; \
 		rm -f $(DESTDIR)/lib/firmware/.dahdi-fw*; \
+		rm -f $(DESTDIR)/lib/firmware/allo-dahdi-fw-*.bin; \
+		rm -f $(DESTDIR)/lib/firmware/.allo-dahdi-fw*; \
 	fi
 
 make_firmware_object: make_firmware_object.in ../dahdi-base.o
